version: '3.9'

services:
  short-url:
    image: vpbuyanov/short-url:latest
    container_name: short-url
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      shortener:

networks:
  shortener: